### ISSUE TITLE
Website Requests

### ISSUE THREAD

**Issue by SDXC** [fmd-project-team/FMD#351]
All website requests will be listed here. Checked entries have been implemented and will be removed from this list some time later.

Create an issue to request new websites (always check here before). After I added your request to the list, I will close your issue and link it to this list.

- [ ] 11Toon `www.11toon.com` (#295)
- [ ] 3li `www.3li.cc` (#315)
- [ ] 700mh `www.700mh.com` (#208)
- [ ] 8muses `www.8muses.com/comics` (#340)
- [ ] AOC `aoc.moe` (#210)
- [ ] BacaManga `bacamanga.co` (#340)
- [ ] BacaManhwa `bacamanhwa.me` (#340)
- [ ] Ciayo `www.ciayo.com` (#113)
- [ ] ComicBorder `comicborder.com` (#313)
- [ ] ComicClear `www.comic-clear.jp` (#313)
- [ ] ComicDays `comic-days.com` (#313)
- [ ] ComicMeteor `comic-meteor.jp` (#313)
- [ ] ComicRyu `comic-ryu.jp` (#313)
- [ ] ComicWalker `comic-walker.com` (#124)
- [ ] Coolmic `coolmic.me` (#88)
- [ ] Daum `webtoon.daum.net` (#186)
- [ ] Erofus `www.erofus.com` (#340)
- [ ] FAKKU `fakku.net` (#220)
- [ ] FreeAdultComix `freeadultcomix.com` (#340)
- [ ] GanganOnline `www.ganganonline.com` (#313)
- [ ] Ganma `ganma.jp` (#313)
- [ ] GetManhwa `getmanhwa.com` (#309)
- [ ] Gntai `www.gntai.xyz` (#323)
- [ ] GoKomik `gokomik.com` (#113)
- [ ] HeavenManga `heavenmanga.com` (#171)
- [ ] HeavenMangaVIP `heavenmanga.vip` (#340)
- [ ] Kakao `page.kakao.com` (#274)
- [ ] KuaikanManhua `www.kuaikanmanhua.com` (#318)
- [ ] KurageBunch `kuragebunch.com` (#313)
- [ ] LaComics `lacomics.org` (#340)
- [ ] Lezhin `www.lezhin.com` (#134)
- [ ] Manamoa `manamoa.net` (#296)
- [ ] MangaBat `mangabat.com/web` (#340)
- [ ] MangaCross `mangacross.jp` (#313)
- [ ] MangaDropoutNet `mangadropout.net` (#113)
- [ ] MangaDrouput `mangadropout.com` (#340)
- [ ] MangaHostBR `br.mangahost.com` (#171)
- [ ] MangaIro `mangairo.com` (#340)
- [ ] MangaLine `manga.line.me` (#313)
- [ ] MangaMX `manga-mx.com` (#171)
- [ ] MangaNelo `manganelo.com` (#340)
- [ ] MangaParkJP `manga-park.com` (#313)
- [ ] MangaSoul `mangasoul.com` (#91)
- [ ] MangaTensei `mangatensei.com` (#188)
- [ ] MangaZukiRaws `raws.mangazuki.co` (#217)
- [ ] Mangaz `www.mangaz.com` (#313)
- [ ] MangazukiClub `mangazuki.club` (#340)
- [ ] MangazukiMe `mangazuki.me` (#340)
- [ ] Manhua123 `www.manhua123.net` (#111)
- [ ] ManhuaBox `manhuabox.net` (#175)
- [ ] ManhwaClub `manhwa.club` (#333)
- [ ] MeganeBuk `www.meganebuk.net` (#89)
- [ ] Mhkan `www.mhkan.com` (#219)
- [ ] MultPorn `multporn.net` (#340)
- [ ] MyHentaiGallery `myhentaigallery.com` (#340)
- [ ] Naver `comic.naver.com` (#348)
- [ ] Ngomik `www.ngomik.in` (#113)
- [ ] OneManhua `www.onemanhua.com` (#315)
- [ ] OnePieceTube `onepiece-tube.com` (#327)
- [ ] OneShotScans `oneshotscans.com` (#297)
- [ ] Piccoma `piccoma.com` (#218)
- [ ] Pixiv `comic.pixiv.net` (#313)
- [ ] PornComixOnline `www.porncomixonline.net` (#340)
- [ ] ReOnComics `www.reoncomics.com` (#113)
- [ ] SeigaNicoManga `seiga.nicovideo.jp/manga` (#313)
- [ ] ShonenJumpPlus `shonenjumpplus.com` (#313)
- [ ] ShonenMagazine `pocket.shonenmagazine.com` (#313)
- [ ] Shueisha `mangaplus.shueisha.co.jp` (#62)
- [ ] SimplyHentai `www.simply-hentai.com` (#340)
- [ ] SukaHentai `sukahentai.com` (#340)
- [ ] Sukima `www.sukima.me/book/search/?free=1` (#313)
- [ ] SvsComics `svscomics.com` (#340)
- [ ] TakeshoboGamma `webcomicgamma.takeshobo.co.jp` (#313)
- [ ] TakeshoboGammaPlus `gammaplus.takeshobo.co.jp` (#313)
- [ ] TakeshoboMangaLifeWin `mangalifewin.takeshobo.co.jp` (#313)
- [ ] TaoManhua `www.taomanhua.com` (#315)
- [ ] Toomics `global.toomics.com` (#144)
- [ ] TopToon `toptoon.net` (#312)
- [ ] UraSunday `urasunday.com` (#313)
- [ ] ValhallaScans `valhallascans.com` (#144)
- [ ] WeComics `m.wecomics.com` (#206)
- [ ] WebAction `webaction.jp` (#313)
- [ ] WebComicsApp `www.webcomicsapp.com` (#187)
- [ ] WebComicsID `www.webcomics.co.id` (#113)
- [ ] WebNovel `www.webnovel.com` (#86)
- [ ] WebtoonsTranslate `translate.webtoons.com` (#106)
- [ ] Xlecx `xlecx.com` (#340)
- [ ] YaoiHavenReborn `www.yaoihavenreborn.com` (#182)
- [ ] ZeroScans `zeroscans.com` (#340)
- [ ] Zymk `www.zymk.cn` (#315)

"Premium-only" websites won't be implemented by me. I'll happily accept pull requests but that's it.
