### ISSUE TITLE
User Asked Features

### ISSUE THREAD

**Issue by Tmp341** [fmd-project-team/FMD#646]
All FMD feature requests will be listed here. We are just compiling them in one issue, so we can focus on high priority issues first. Checked entries have been implemented and will be removed from this list some time later.

Create an issue to request features (always check here before). After we added your request to the list, we will close your issue and link it to this list.

Please check first, if the request has already been implemented
https://github.com/orgs/fmd-project-team/projects/4
  
Don't make requests for crosslined features, as they are already rejected, impossible to implement or takes too much time to do.
  
---

- [ ] Add HTTPS support for proxy connections (#36)
- [ ] Add language filter [HitomiLa] (#238)
- [ ] Add rename digits numbering (#560)
